@startuml

package "EIS App" {
HTTP - [First Component]
[EIS Billing]
[EIS Commissions]
[EIS Claims]
[Payment Transfer Job]
[Payment Confirmation Job]
[Apache Camel]
}

database EIS-DB {

}

artifact hello

package "Other Groups" {
FTP - [Second Component]

[First Component] --> FTP
}

@enduml