@startuml
allowmixing

left to right direction



skinparam package {
  BackgroundColor<<LIB>> olive
  BorderColor<<LIB>> olive
}

skinparam artifact {
  BackgroundColor yellow
  BorderColor brown
}

enum TransferStatus {
pending
sent
processed
}

enum ProcessingStatus {
stopped
cleared
declined
}

class PaymentUpdatedEvent
class PaymentTransferEntity {
Long batchNumber
String transitNumber
TransferStatus statusCd
Date updated
Boolean voided
String paymentNumber
int direction
BigDecimal amount
String currency
String referenceNumber
ProcessingStatus processingStatus
String declineReason
...
}


PaymentTransferEntity *--> TransferStatus
PaymentTransferEntity *--> ProcessingStatus

EISUPaymentTransferJob o--> EISUPaymentStagingService



class EISUPaymentUpdatedEventListener {
+onApplicationEvent(paymentUpdatedEvent)
}

EISUPaymentUpdatedEventListener o--> PaymentUpdatedEvent

interface EISUPaymentStagingService
class EISUPaymentStagingServiceImpl{
+createUpdateStagingRecord(paymentUpdatedEvent event)
+updateStagingRecord(paymentTransferProcessingDTO)
+fetchStagingRecords(dateFrom, batchNumber)
+cleanup(dateTo)
}

EISUPaymentStagingServiceImpl *--> PaymentTransferProcessingDTO

class EISUPaymentTransferJob {
+JobResults doExecute(map,auditor)
}
note "synchronous" as S
S . EISUPaymentTransferJob

class EISUPaymentResponseJob {
+JobResults doExecute(map,auditor)
}
S . EISUPaymentTransferJob

EISUPaymentTransferJob o--> EISUPaymentTransferService
EISUPaymentTransferJob o--> EISUPaymentStagingService




interface EISUPaymentTransferService
class EISUPaymentTransferServiceImpl{
+validateStagingRecord(paymentTransferEntity)
+mapStagingRecord(paymentTransferEntity)
}

EISUPaymentTransferServiceImpl o--> ProducerTemplate
EISUPaymentTransferServiceImpl o--> PaymentTransferEntity
EISUPaymentStagingJpaDao o--> PaymentTransferEntity

package Camel <<LIB>> {
artifact "SFTP component"
interface RouteBuilder
interface Processor
interface ProducerTemplate {
+sendBodyAndHeader(endpointUri,body,headerName,headerValue)
}
}

EISUPaymentTransferService *--> EISUPaymentResponseRouteBuilder


class EISUPaymentResponseRouteBuilder {
+configure()
}
EISUPaymentResponseRouteBuilder ..|> RouteBuilder
EISUPaymentResponseRouteBuilder *--> EISUPaymentResponseProcessor
EISUPaymentResponseRouteBuilder o--> "SFTP component"

class EISUPaymentTransferRouteBuilder {
+configure()
}
EISUPaymentTransferRouteBuilder ..|> RouteBuilder
EISUPaymentTransferRouteBuilder *--> EISUPaymentTransferPostProcessor
EISUPaymentTransferRouteBuilder o--> "SFTP component"

class EISUPaymentTransferPostProcessor {
+process(exchange)
-updateStagingRecords(batchNumber)
-updatePayments(batchNumber)
}

EISUPaymentTransferPostProcessor ..|> Processor
EISUPaymentTransferPostProcessor o--> EISUPaymentStagingDao

package BeanIO <<LIB>> {
abstract class BeanIOStreamFactory
interface BeanWriter
interface BeanReader

BeanIOStreamFactory --> "creates" BeanWriter
BeanIOStreamFactory --> "creates" BeanReader
}
artifact "payment transfer mapping xml file"
artifact "payment response mapping xml file"


EISUPaymentTransferServiceImpl *--> BeanWriter
EISUPaymentTransferServiceImpl *--> BeanReader

BeanIOStreamFactory *-> "payment transfer mapping xml file"
BeanIOStreamFactory *--> "payment response mapping xml file"




EISUPaymentTransferJob o--> EISUPaymentStagingService
EISUPaymentTransferJob o--> EISUPaymentTransferService

EISUPaymentTransferServiceImpl --|> EISUPaymentTransferService

class PaymentTransferProcessingDTO {
String paymentNumber
ProcessingStatus processingStatus
String declineReason
....
}
EISUPaymentStagingServiceImpl ..|> EISUPaymentStagingService
EISUPaymentUpdatedEventListener --> EISUPaymentStagingService

interface EISUPaymentStagingDao
class EISUPaymentStagingJpaDao
EISUPaymentStagingJpaDao ..|> EISUPaymentStagingDao

EISUPaymentStagingServiceImpl *--> EISUPaymentStagingDao
@enduml