@startuml

left to right direction

skinparam  package {

	BackgroundColor<<EXTERNAL>> YellowGreen
	BorderColor<< EXTERNAL >> YellowGreen

}

skinparam component {
  BackgroundColor<<FRAMEWORK>> orange
  BorderColor<< FRAMEWORK >> orange

}

skinparam component {
  BackgroundColor<<EIS>> olive
  BorderColor<<EIS>> olive

}


package "EIS Batch App" {
[Billing]<<EIS>>
[Commissions]<<EIS>>
[Claims]<<EIS>>
[Payment Transfer Job]
[Payment Response Job]
[Payment Clearing Job]
[Payment Staging Layer]
[Apache Camel]<<FRAMEWORK>>
[Payment Transfer Layer]
}

package "Payment Gateway"<< EXTERNAL >> {
SFTP - [File Exchange]
[Payment Processing]
}

[File Exchange] <--> [Payment Processing]

[Payment Transfer Layer] --> [Apache Camel]

[Apache Camel] --> SFTP
[Billing] -> [Payment Staging Layer]
[Commissions] -> [Billing]
[Claims]  -> [Billing]
[Payment Transfer Job] -> [Payment Transfer Layer]
[Payment Response Job] -> [Payment Transfer Layer]
[Payment Transfer Job] -----> [Payment Staging Layer]
[Payment Response Job] -> [Payment Staging Layer]
[Payment Clearing Job] -> [Payment Staging Layer]
[Payment Clearing Job] --> [Billing]




@enduml