@startuml
skinparam  participant {
  BackgroundColor yellow
  BorderColor brown
}

actor "Job Scheduler"
participant EISUPaymentTransferJob
participant EISUPaymentStagingServiceImpl
participant EISUPaymentTransferServiceImpl
participant EISUCheckPaymentTransferMapperImpl
participant EISUEFTPaymentTransferMapperImpl
participant StreamFactory #lightgray
participant BeanWriter #lightgray
participant ProducerTemplate #lightgray
participant EISUPaymentTransferRouteBuilder
participant "SFTP component" #lightgray
participant EISUPaymentTransferPostProcessor



"Job Scheduler" ->o EISUPaymentTransferJob : run
EISUPaymentTransferJob -> EISUPaymentTransferJob ++: doExecute
EISUPaymentTransferJob -> EISUPaymentTransferJob ++ : fetchCheckPayments
EISUPaymentTransferJob -> EISUPaymentStagingServiceImpl ++ : fetchStagingRecords
return
return

EISUPaymentTransferJob -> EISUPaymentTransferJob ++ : fetchEFTPayments
EISUPaymentTransferJob -> EISUPaymentStagingServiceImpl ++: fetchStagingRecords
return
return

EISUPaymentTransferJob -> EISUPaymentTransferServiceImpl ++ : transferCheckPayments
EISUCheckPaymentTransferMapperImpl ->o StreamFactory :createWriter
loop "all check payments"
EISUPaymentTransferServiceImpl -> EISUCheckPaymentTransferMapperImpl ++ :validateStagingRecord
return
EISUPaymentTransferServiceImpl -> EISUCheckPaymentTransferMapperImpl ++ :mapStagingRecord
note over EISUCheckPaymentTransferMapperImpl #aqua :payment transfer CHECK mapping xml file
EISUCheckPaymentTransferMapperImpl -> BeanWriter ++ :write
return

return
end
EISUPaymentTransferServiceImpl -> ProducerTemplate : sendBodyAndHeader
ProducerTemplate -[#blue]>o EISUPaymentTransferRouteBuilder:configure
ProducerTemplate -[#blue]>o "SFTP component":send
note over "SFTP component" #aqua : retry N times on fail with timeout M
ProducerTemplate -[#blue]>o EISUPaymentTransferPostProcessor:process
EISUPaymentTransferPostProcessor -> EISUPaymentTransferPostProcessor:updateStagingRecords
EISUPaymentTransferPostProcessor -> EISUPaymentTransferPostProcessor:updatePayments
return

EISUPaymentTransferJob -> EISUPaymentTransferServiceImpl ++ : transferEFTPayments
EISUCheckPaymentTransferMapperImpl ->o StreamFactory :createWriter
loop "all EFT payments"
EISUPaymentTransferServiceImpl -> EISUCheckPaymentTransferMapperImpl ++ :validateStagingRecord
return
EISUPaymentTransferServiceImpl -> EISUCheckPaymentTransferMapperImpl ++ :mapStagingRecord
note over EISUCheckPaymentTransferMapperImpl #aqua :payment transfer EFT mapping xml file
EISUCheckPaymentTransferMapperImpl -> BeanWriter ++ :write
return

return
end
EISUPaymentTransferServiceImpl -> ProducerTemplate : sendBodyAndHeader
ProducerTemplate -[#blue]>o EISUPaymentTransferRouteBuilder:configure
note over EISUPaymentTransferRouteBuilder #aqua : retry N times on fail with timeout M
ProducerTemplate -[#blue]>o "SFTP component":send
ProducerTemplate -[#blue]>o EISUPaymentTransferPostProcessor:process
EISUPaymentTransferPostProcessor -> EISUPaymentTransferPostProcessor:updateStagingRecords
EISUPaymentTransferPostProcessor -> EISUPaymentTransferPostProcessor:updatePayments
return


@enduml




@enduml