@startuml
allowmixing

left to right direction



skinparam package {
  BackgroundColor<<LIB>> olive
  BorderColor<<LIB>> olive
}

skinparam artifact {
  BackgroundColor lightgreen
  BorderColor brown
}



interface EISUPaymentStagingService


class EISUPaymentTransferJob {
+JobResults doExecute(map,auditor)
-fetchCheckPayments(date, batchNumber)
-fetchEFTPayments(date, batchNumber)
}
note   "synchronous" as S #aqua
S . EISUPaymentTransferJob





interface EISUPaymentTransferService{

}
class EISUPaymentTransferServiceImpl{
+transferCheckPayments(checkPaymentTransferEntities)
+transferEFTPayments(checkPaymentTransferEntities)
}

interface EISUPaymentTransferMapper {

}

class EISUCheckPaymentTransferMapperImpl{
 +validateStagingRecord(paymentTransferEntity)
 +mapStagingRecord(paymentTransferEntity)
}

EISUCheckPaymentTransferMapperImpl ..|>  EISUPaymentTransferMapper
class EISUEFTPaymentTransferMapperImpl{
 +validateStagingRecord(paymentTransferEntity)
 +mapStagingRecord(paymentTransferEntity)
}

EISUEFTPaymentTransferMapperImpl ..|>  EISUPaymentTransferMapper

EISUPaymentTransferServiceImpl *->  EISUPaymentTransferMapper

EISUPaymentTransferServiceImpl o--> ProducerTemplate


package Camel <<LIB>> {
component "SFTP component"
interface RouteBuilder
interface Processor
interface ProducerTemplate {
+sendBodyAndHeader(endpointUri,body,headerName,headerValue)
}
}



EISUPaymentTransferRouteBuilder ..|> RouteBuilder
EISUPaymentTransferRouteBuilder *--> EISUPaymentTransferPostProcessor
EISUPaymentTransferRouteBuilder o-> "SFTP component"

note top of EISUPaymentTransferRouteBuilder #aqua : creates separate routes to process check and EFT payments



class EISUPaymentTransferRouteBuilder {
+configure()
}




class EISUPaymentTransferPostProcessor {
+process(exchange)
-updateStagingRecords(batchNumber)
-updatePayments(batchNumber)
}

note as PRA #aqua
<b>updateStagingRecords</b> method
is used to update transferStatus and updated date
 <b>updatePayments</b> method invokes BASE service
 to move approved claim payment to issued.

end note

PRA . EISUPaymentTransferPostProcessor

EISUPaymentTransferPostProcessor ..|> Processor
EISUPaymentTransferPostProcessor o--> EISUPaymentStagingService

package BeanIO <<LIB>> {
abstract class StreamFactory
interface BeanWriter


StreamFactory --> "creates" BeanWriter
}
artifact "payment transfer CHECK mapping xml file"
artifact "payment transfer EFT mapping xml file"


EISUCheckPaymentTransferMapperImpl o-> BeanWriter
EISUEFTPaymentTransferMapperImpl o-> BeanWriter
EISUPaymentTransferServiceImpl *--> EISUPaymentTransferRouteBuilder

StreamFactory *-> "payment transfer CHECK mapping xml file"
StreamFactory *-> "payment transfer EFT mapping xml file"


EISUPaymentTransferJob o-> EISUPaymentStagingService
EISUPaymentTransferJob o--> EISUPaymentTransferService

EISUPaymentTransferServiceImpl --|> EISUPaymentTransferService

ProducerTemplate ..> EISUPaymentTransferRouteBuilder




@enduml