@startuml

skinparam  participant {
  BackgroundColor yellow
  BorderColor brown
}

actor Billing
actor Commissions
actor Claims

participant EISUPaymentUpdatedEventListener
participant EISUPaymentStagingService
participant EISUPaymentStagingDao


Billing ->o EISUPaymentUpdatedEventListener : generate PaymentUpdatedEvent
Commissions ->o EISUPaymentUpdatedEventListener : generate PaymentUpdatedEvent
Claims ->o EISUPaymentUpdatedEventListener : generate PaymentUpdatedEvent

EISUPaymentUpdatedEventListener -> EISUPaymentUpdatedEventListener ++ :onApplicationEvent
opt "payment qualifies for staging"
EISUPaymentUpdatedEventListener -> EISUPaymentStagingService ++ : stagePayment
EISUPaymentStagingService -> EISUPaymentStagingDao ++ :retrievePaymentForStaging
return
EISUPaymentStagingService -> EISUPaymentStagingDao ++ :createUpdateStagingRecord
return
return
end

opt "void payment"
EISUPaymentUpdatedEventListener -> EISUPaymentStagingService ++ : voidPayment
EISUPaymentStagingService -> EISUPaymentStagingDao ++ :voidPayment
return
return
end

@enduml