@startuml



skinparam  package {

	BackgroundColor<<EXTERNAL>> YellowGreen
	BorderColor<< EXTERNAL >> YellowGreen
	BackgroundColor<<DB>> plum
    BorderColor<<DB>> plum

}



package "Payment Gateway"<< EXTERNAL >> {
SFTP - [Payment Gateway]
}


package "Web"{

node "Web LB"

node "EIS Web App 1" {
[EIS App 3]
}

node "EIS Web App 2" {
[EIS App 4]
}

(Web LB) --> (EIS App 3)
(Web LB) --> (EIS App 4)

note "EIS Web Apps only create/update payments" as N1

(EIS App 3) -- N1
N1 -- (EIS App 4)
}

package "Batch" {

node "EIS Batch App 1" {
[EIS App 1]
}

node "EIS Batch App 2" {
[EIS App 2]
}

note "EIS Batch Apps create, update, transfer and post-process payments" as N2

(EIS App 1) -- N2
N2 -- (EIS App 2)
}


package "DB"<<DB>> {

[DB Load Balancer]

database DBInstance1 {
[EIS DB 1]
}

database DBInstance2  {
[EIS DB 2]
}

[DB Load Balancer] ---> [EIS DB 1]
[DB Load Balancer] ---> [EIS DB 2]

[Shared Storage]

[EIS DB 1] ---> [Shared Storage]
[EIS DB 2] ---> [Shared Storage]

JDBC - [DB Load Balancer]

}
[EIS App 1] ------ JDBC
[EIS App 2] ------ JDBC
[EIS App 3] ------ JDBC
[EIS App 4] ------ JDBC
[EIS App 1] -------- SFTP
[EIS App 2] -------- SFTP





@enduml