@startuml

allowmixing

class RestPreconfigAutoPolicyDetailsInfo{

}
note top of RestPreconfigAutoPolicyDetailsInfo #aqua : customised preconfig DTO



class AbstractPreconfigRestService

class EISUAutoQuoteRestServiceImpl{
+createQuote(request)
+updateQuote(request, policyNumber)
+getQuote(policyNumber)
+rateQuote(policyNumber)
+issueQuote(policyNumber, ctx)
-mapCreateResponse
}

EISUAutoQuoteRestServiceImpl --|> AbstractPreconfigRestService

EISUAutoQuoteRestServiceImpl ..> RestPreconfigAutoPolicyDetailsInfo

interface RestQuoteFacade #moccasin{
}

interface MapperRegistry{
+getMapper(classFrom, classTo)
}

note top of MapperRegistry #aqua : separate REST-to-Domain and Domain-to-REST mapper registries

interface Mapper #moccasin{
+map(from)
}

MapperRegistry o--> EISURestPolicyInfoMapper
MapperRegistry o--> EISURestDriverPartyInfoMapper



RestPolicyInfoMapper ..|> Mapper
EISURestPolicyInfoMapper --|> RestPolicyInfoMapper

RestDriverPartyInfoMapper ..|> Mapper
EISURestDriverPartyInfoMapper --|> RestDriverPartyInfoMapper


class EISURestPolicyInfoMapper {
 +map(PolicySearchResult source, RestPolicyInfo target)
}

class EISURestDriverPartyInfoMapper {
 +map(DriverInfo source, RestDriverInfo target)
}

note "There are several mappers, those 2 are just examples" as N2
EISURestPolicyInfoMapper .. N2
N2 .. EISURestDriverPartyInfoMapper

class RestPreconfigAutoQuoteFacadeAdapter {
createQuote(componentName, version,productCd, quoteInfo)
getQuoteDetails(String policyNumber)
}

RestQuoteProcessor o--> QuoteLifecycleService



class  PrecofigRestProcessorHelper {
retriveComponentConfigurations(productCd, version)
+genComponentInfo(parent, componentName, configurations)
}



RestPreconfigAutoQuoteFacadeAdapter ..|> RestQuoteFacade


interface QuoteLifecycleService #moccasin{
+rate(quote, txInfo)
+save(quote)
+issue(quote, txInfo)
}


interface PackageFacade #moccasin{
evalTable(tableName, root, instance,context)
getAvailablePackages(root,instance,context)
}

abstract class RestQuoteProcessor


RestPreconfigAutoQuoteFacadeAdapter *-> RestQuoteProcessor

class RestPreconfigCreationQuoteProcessor{
+processor(productCd,version,request,componentName)

}


class RestPreconfigRetrievalQuoteProcessor {
+processor(request)
}

class RestPreconfigEndorsementQuoteProcessor{
+processor(request)
}

class RestPreconfigRateQuoteProcessor {
+processor(policyNumber)
}

class RestPreconfigIssueQuoteProcessor {
+processor(policyNumber,issueContext)
}

interface PurchaseProcessingService #moccasin{
+processPurchaseRequest()
}

class EISUPurchaseServiceCreateDepositPaymentImpl {
+createDepositPayment(account, policyTerm, downPaymentWorker, purchaseQuoteInfoDto)
}


RestPreconfigRetrievalQuoteProcessor ..|> RestQuoteProcessor
RestPreconfigEndorsementQuoteProcessor ..|> RestQuoteProcessor

RestPreconfigCreationQuoteProcessor ..|> RestQuoteProcessor
RestPreconfigRateQuoteProcessor ..|> RestQuoteProcessor
RestPreconfigIssueQuoteProcessor ..|> RestQuoteProcessor

RestPreconfigIssueQuoteProcessor o--> PurchaseProcessingService
PurchaseProcessingService *--> EISUPurchaseServiceCreateDepositPaymentImpl

class ComponentInfoHandler{
+validateBlsRulesFromConstraints(policy, status)
+validateBlsRulesByTag(policy, tag)
+validatePolicyLocked(policyNumber)
+retrivePolicySummary(policyNumber)
}





EISUAutoQuoteRestServiceImpl o--> RestPreconfigAutoQuoteFacadeAdapter


RestQuoteProcessor o--> MapperRegistry
RestQuoteProcessor o--> PrecofigRestProcessorHelper
RestQuoteProcessor o--> PackageFacade
RestQuoteProcessor o--> ComponentInfoHandler
RestQuoteProcessor ..> PolicyDao
RestQuoteProcessor ..> PolicyFacade




@enduml