@startuml

skinparam  participant {
  BackgroundColor yellow
  BorderColor brown
}

actor DXP

participant EISUAutoQuoteRestServiceImpl
participant RestPreconfigAutoQuoteFacadeAdapter
participant RestPreconfigRateQuoteProcessor
participant PolicyDao #moccasin
participant ComponentInfoHandler
participant QuoteLifecycleService #moccasin

DXP ->o EISUAutoQuoteRestServiceImpl:rateQuote
EISUAutoQuoteRestServiceImpl --> RestPreconfigAutoQuoteFacadeAdapter ++: rateQuote
RestPreconfigAutoQuoteFacadeAdapter --> RestPreconfigRateQuoteProcessor ++: process
RestPreconfigRateQuoteProcessor --> ComponentInfoHandler++:validatePolicyLocked
return
RestPreconfigRateQuoteProcessor --> PolicyDao ++ :findPendingQuotesForPolicy
return
RestPreconfigRateQuoteProcessor --> PolicyDao ++ :findById
return
RestPreconfigRateQuoteProcessor --> ComponentInfoHandler++:validateBlsRulesFromConstraints
note over ComponentInfoHandler #aqua: run rules for dataGather process
return
RestPreconfigRateQuoteProcessor --> RestPreconfigRateQuoteProcessor ++:runAdditionalValidations
return
RestPreconfigRateQuoteProcessor --> QuoteLifecycleService ++:rate
return
RestPreconfigRateQuoteProcessor --> QuoteLifecycleService ++:save
return
return
return
EISUAutoQuoteRestServiceImpl --> EISUAutoQuoteRestServiceImpl :mapRateResponse





@enduml