@startuml


Customer -> "1" (Register)
Customer --> "2" (Create Quote)
Customer --> "3" (Retrieve Quote)
Customer --> "4/5" (Rate Quote)
Customer --> "4/5" (Update Quote)
(Rate Quote) .> (Rate Quote Variations) :extend
Customer ---> "6" (Purchase Policy)
(Purchase Policy) .> (Make Payment) :include


@enduml