@startuml


Customer -> "1" (Register)
Customer --> "2" (Create Quote)
Customer --> "3/4" (Rate Quote)
Customer --> "3/4" (Update Quote)
(Rate Quote) .> (Rate Quote Variations) :extend
Customer ---> "5" (Purchase policy)
(Purchase policy) .> (Make payment) :include


@enduml